name: "🚀 Publish & Release"

on:
  push:
    branches: [master]
  # release:
    # types: [published]
    # types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2
      - name: 🟢 node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      # - run: npm version _
      # - run: npm push

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2
      - name: 🟢 node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  publish-gpr:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: 📚 checkout
          uses: actions/checkout@v2
        - name: 🟢 node
          uses: actions/setup-node@v2
          with:
            node-version: 12
            registry-url: https://npm.pkg.github.com/
            # scope: 'awwmicky'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_AUTH_TOKEN}}
